# Generated by Django 3.1.4 on 2020-12-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_followers',
        ),
    ]
